% Stereo-Rig Cams 2 and 1 First Calibration
% Michael Millard
% Date: 16/09/2022

% Camera 2 on the left, camera 1 on the right

% Camera 2 images first
imageFileNames1 = {'..\Project_Pics\Calibration1\Cams21\Cam2\cams12_1_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_2_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_3_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_4_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_5_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_6_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_7_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_8_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_9_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_10_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_11_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_12_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_13_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_14_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_15_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_16_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_17_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_18_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_19_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_20_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_21_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam2\cams12_22_cam2.bmp',...
    };

% Camera 1 images second
imageFileNames2 = {'..\Project_Pics\Calibration1\Cams21\Cam1\cams12_1_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_2_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_3_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_4_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_5_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_6_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_7_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_8_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_9_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_10_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_11_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_12_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_13_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_14_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_15_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_16_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_17_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_18_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_19_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_20_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_21_cam1.bmp',...
    '..\Project_Pics\Calibration1\Cams21\Cam1\cams12_22_cam1.bmp',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
squareSize = 10;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams1Cams21, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

if 1
    % View reprojection errors
    h1=figure; showReprojectionErrors(stereoParams1Cams21);

    % Visualize pattern locations
    h2=figure; showExtrinsics(stereoParams1Cams21, 'CameraCentric');

    % Display parameter estimation errors
    displayErrors(estimationErrors, stereoParams1Cams21);
end
