% Stereo-Rig Cams 3 and 2 First Calibration
% Michael Millard
% Date: 16/09/2022

% Camera 3 on the left, camera 2 on the right

% Camera 3 images first
imageFileNames1 = {'..\Project_Pics\Calibration1\Cams32\Cam3\cams23_1_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_2_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_3_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_4_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_5_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_6_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_7_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_8_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_9_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_10_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_11_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_12_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_13_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_14_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_15_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_16_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_17_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_18_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_19_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_20_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_21_cam3.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam3\cams23_22_cam3.bmp',...
    };

% Camera 2 images second
imageFileNames2 = {'..\Project_Pics\Calibration1\Cams32\Cam2\cams23_1_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_2_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_3_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_4_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_5_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_6_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_7_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_8_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_9_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_10_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_11_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_12_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_13_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_14_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_15_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_16_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_17_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_18_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_19_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_20_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_21_cam2.bmp',...
    '..\Project_Pics\Calibration1\Cams32\Cam2\cams23_22_cam2.bmp',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
squareSize = 10;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams1Cams32, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

if 1
    % View reprojection errors
    h1=figure; showReprojectionErrors(stereoParams1Cams32);

    % Visualize pattern locations
    h2=figure; showExtrinsics(stereoParams1Cams32, 'CameraCentric');

    % Display parameter estimation errors
    displayErrors(estimationErrors, stereoParams1Cams32);
end
